development:
  adapter: postgresql
  encoding: unicode
  database: sfrailsapp_development
  pool: 5
  username: sfrailsapp
  password:
  template: template0 # Required for UTF8 encoding

test:
  adapter: postgresql
  encoding: unicode
  database: sfrailsapp_test
  pool: 5
  username: sfrailsapp
  password:
  template: template0 # Required for UTF8 encoding

production:
  adapter: postgresql
  encoding: unicode
  database: sfrailsapp_production
  pool: 5
  username: sfrailsapp
  password:
  template: template0 # Required for UTF8 encoding
